# Generated by Django 3.0.8 on 2020-07-07 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoroscopeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('sign_name', models.TextField(blank=True)),
                ('date_range', models.TextField(blank=True)),
                ('current_date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True)),
                ('compatibility', models.TextField(blank=True)),
                ('mood', models.TextField(blank=True)),
                ('color', models.TextField(blank=True)),
                ('lucky_number', models.TextField(blank=True)),
                ('lucky_time', models.TextField(blank=True)),
            ],
        ),
    ]
